"""Canonical skill alias map for the resume matching engine."""

from __future__ import annotations

SKILL_ALIASES: dict[str, str] = {
    "python":                       "python",
    "python programming":           "python",
    "java":                         "java",
    "java programming":             "java",
    "javascript":                   "javascript",
    "java script":                  "javascript",
    "js":                           "javascript",
    "typescript":                   "typescript",
    "ts":                           "typescript",
    "c++":                          "c++",
    "cpp":                          "c++",
    "c plus plus":                  "c++",
    "c#":                           "c#",
    "csharp":                       "c#",
    "c sharp":                      "c#",
    "r":                            "r",
    "go":                           "go",
    "golang":                       "go",
    "rust":                         "rust",
    "kotlin":                       "kotlin",
    "swift":                        "swift",
    "php":                          "php",
    "ruby":                         "ruby",
    "scala":                        "scala",
    "perl":                         "perl",
    "matlab":                       "matlab",
    "solidity":                     "solidity",
    "dart":                         "dart",
    "react":                        "react",
    "reactjs":                      "react",
    "react.js":                     "react",
    "angular":                      "angular",
    "angularjs":                    "angular",
    "vue":                          "vue",
    "vue.js":                       "vue",
    "vuejs":                        "vue",
    "html":                         "html",
    "html5":                        "html",
    "css":                          "css",
    "css3":                         "css",
    "sass":                         "sass",
    "scss":                         "sass",
    "bootstrap":                    "bootstrap",
    "tailwind":                     "tailwind",
    "tailwindcss":                  "tailwind",
    "next.js":                      "next.js",
    "nextjs":                       "next.js",
    "nuxt.js":                      "nuxt.js",
    "nuxtjs":                       "nuxt.js",
    "node.js":                      "node.js",
    "nodejs":                       "node.js",
    "node js":                      "node.js",
    "express":                      "express",
    "express.js":                   "express",
    "django":                       "django",
    "flask":                        "flask",
    "fastapi":                      "fastapi",
    "fast api":                     "fastapi",
    "spring boot":                  "spring boot",
    "springboot":                   "spring boot",
    "spring":                       "spring",
    "laravel":                      "laravel",
    "ruby on rails":                "ruby on rails",
    "rails":                        "ruby on rails",
    "sql":                          "sql",
    "mysql":                        "mysql",
    "postgresql":                   "postgresql",
    "postgres":                     "postgresql",
    "sqlite":                       "sqlite",
    "mongodb":                      "mongodb",
    "mongo":                        "mongodb",
    "redis":                        "redis",
    "cassandra":                    "cassandra",
    "elasticsearch":                "elasticsearch",
    "oracle":                       "oracle",
    "firebase":                     "firebase",
    "dynamodb":                     "dynamodb",
    "amazon web services":          "aws",
    "aws":                          "aws",
    "microsoft azure":              "azure",
    "azure":                        "azure",
    "google cloud platform":        "gcp",
    "google cloud":                 "gcp",
    "gcp":                          "gcp",
    "docker":                       "docker",
    "kubernetes":                   "kubernetes",
    "k8s":                          "kubernetes",
    "terraform":                    "terraform",
    "ansible":                      "ansible",
    "jenkins":                      "jenkins",
    "github actions":               "github actions",
    "gitlab ci":                    "gitlab ci",
    "ci/cd":                        "ci/cd",
    "cicd":                         "ci/cd",
    "linux":                        "linux",
    "ubuntu":                       "linux",
    "shell scripting":              "bash",
    "bash":                         "bash",
    "nginx":                        "nginx",
    "machine learning":             "machine learning",
    "ml":                           "machine learning",
    "deep learning":                "deep learning",
    "dl":                           "deep learning",
    "natural language processing":  "nlp",
    "nlp":                          "nlp",
    "computer vision":              "computer vision",
    "cv":                           "computer vision",
    "large language model":         "llm",
    "large language models":        "llm",
    "llm":                          "llm",
    "reinforcement learning":       "reinforcement learning",
    "rl":                           "reinforcement learning",
    "tensorflow":                   "tensorflow",
    "pytorch":                      "pytorch",
    "keras":                        "keras",
    "scikit-learn":                 "scikit-learn",
    "sklearn":                      "scikit-learn",
    "hugging face":                 "hugging face",
    "huggingface":                  "hugging face",
    "openai":                       "openai",
    "feature engineering":          "feature engineering",
    "model deployment":             "model deployment",
    "data science":                 "data science",
    "data scientist":               "data science",
    "data analysis":                "data analysis",
    "data analytics":               "data analysis",
    "data engineering":             "data engineering",
    "pandas":                       "pandas",
    "numpy":                        "numpy",
    "matplotlib":                   "matplotlib",
    "seaborn":                      "seaborn",
    "tableau":                      "tableau",
    "power bi":                     "power bi",
    "powerbi":                      "power bi",
    "excel":                        "excel",
    "apache spark":                 "apache spark",
    "spark":                        "apache spark",
    "hadoop":                       "hadoop",
    "kafka":                        "kafka",
    "apache airflow":               "airflow",
    "airflow":                      "airflow",
    "dbt":                          "dbt",
    "android":                      "android",
    "ios":                          "ios",
    "react native":                 "react native",
    "flutter":                      "flutter",
    "xamarin":                      "xamarin",
    "cybersecurity":                "cybersecurity",
    "cyber security":               "cybersecurity",
    "ethical hacking":              "ethical hacking",
    "penetration testing":          "penetration testing",
    "network security":             "network security",
    "cryptography":                 "cryptography",
    "owasp":                        "owasp",
    "git":                          "git",
    "github":                       "github",
    "gitlab":                       "gitlab",
    "bitbucket":                    "bitbucket",
    "jira":                         "jira",
    "confluence":                   "confluence",
    "agile":                        "agile",
    "scrum":                        "scrum",
    "kanban":                       "kanban",
    "object oriented programming":  "oop",
    "object-oriented programming":  "oop",
    "oop":                          "oop",
    "test driven development":      "tdd",
    "test-driven development":      "tdd",
    "tdd":                          "tdd",
    "system design":                "system design",
    "design patterns":              "design patterns",
    "unit testing":                 "unit testing",
    "microservices":                "microservices",
    "rest api":                     "rest api",
    "restful api":                  "rest api",
    "restful":                      "rest api",
    "graphql":                      "graphql",
    "api":                          "api",
    "blockchain":                   "blockchain",
    "smart contracts":              "smart contracts",
    "smart contract":               "smart contracts",
    "ethereum":                     "ethereum",
    "internet of things":           "iot",
    "iot":                          "iot",
    "augmented reality":            "ar/vr",
    "virtual reality":              "ar/vr",
    "ar/vr":                        "ar/vr",
    "problem solving":              "problem solving",
    "critical thinking":            "critical thinking",
    "project management":           "project management",
    "time management":              "time management",
    "communication":                "communication",
    "teamwork":                     "teamwork",
    "leadership":                   "leadership",
    "research":                     "research",
}

_SORTED_ALIAS_KEYS: list[str] = sorted(SKILL_ALIASES.keys(), key=lambda k: -len(k))
